/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fortuna;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Random;

/**
 *
 * @author jjlui
 */
public class FortunaGrafico extends javax.swing.JFrame {

    /**
     * Creates new form FortunaGrafico
     */
    public void conectar() {
        
        try {
            String host = "localhost";
            int port = 19999;
            StringBuffer mensaje = new StringBuffer();
            
            InetAddress ia = InetAddress.getByName(host);
            Socket connection = new Socket(ia, port);
            
            BufferedOutputStream bos = new BufferedOutputStream(connection.getOutputStream());
            OutputStreamWriter osw = new OutputStreamWriter(bos);
            
            Random r = new Random();
            
            Integer i = r.nextInt(50);
            String s;
            s = i.toString() + (char) 13;
            osw.write(s);
            osw.flush();
            
            BufferedInputStream bis = new BufferedInputStream(connection.getInputStream());
            InputStreamReader isr = new InputStreamReader(bis);
            
            int caracter;
            while ((caracter = isr.read()) != 13) {
                mensaje.append((char) caracter);
            }
            
            area.setText(mensaje.toString());
            
            connection.close();
        } catch (UnknownHostException ex) {
            System.out.println(ex.toString());
            
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
        
    }
    
    public FortunaGrafico() {
        initComponents();
        a.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                conectar();

            }
        });
        
        B.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                conectar();
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        a = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        B = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        y = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        s = new javax.swing.JButton();
        t = new javax.swing.JButton();
        u = new javax.swing.JButton();
        v = new javax.swing.JButton();
        x = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 480, 69, 29);

        a.setText("A");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(140, 120, 50, 29);

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 170, 380, 270);

        B.setText("B");
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BMouseExited(evt);
            }
        });
        getContentPane().add(B);
        B.setBounds(190, 120, 50, 29);

        c.setText("C");
        getContentPane().add(c);
        c.setBounds(240, 120, 50, 29);

        d.setText("D");
        getContentPane().add(d);
        d.setBounds(290, 120, 50, 29);

        e.setText("E");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(340, 120, 50, 29);

        y.setText("Y");
        getContentPane().add(y);
        y.setBounds(340, 240, 50, 29);

        f.setText("F");
        getContentPane().add(f);
        f.setBounds(140, 150, 50, 29);

        g.setText("G");
        getContentPane().add(g);
        g.setBounds(190, 150, 50, 29);

        h.setText("H");
        getContentPane().add(h);
        h.setBounds(240, 150, 50, 29);

        i.setText("I");
        getContentPane().add(i);
        i.setBounds(290, 150, 50, 29);

        j.setText("J");
        getContentPane().add(j);
        j.setBounds(340, 150, 50, 29);

        k.setText("K");
        getContentPane().add(k);
        k.setBounds(140, 180, 50, 29);

        l.setText("L");
        getContentPane().add(l);
        l.setBounds(190, 180, 50, 29);

        m.setText("M");
        getContentPane().add(m);
        m.setBounds(240, 180, 50, 29);

        n.setText("N");
        getContentPane().add(n);
        n.setBounds(290, 180, 50, 29);

        n1.setText("Ñ");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1);
        n1.setBounds(340, 180, 50, 29);

        o.setText("O");
        getContentPane().add(o);
        o.setBounds(140, 210, 50, 29);

        p.setText("P");
        getContentPane().add(p);
        p.setBounds(190, 210, 50, 29);

        q.setText("Q");
        getContentPane().add(q);
        q.setBounds(240, 210, 50, 29);

        r.setText("R");
        getContentPane().add(r);
        r.setBounds(290, 210, 50, 29);

        s.setText("S");
        getContentPane().add(s);
        s.setBounds(340, 210, 50, 29);

        t.setText("T");
        getContentPane().add(t);
        t.setBounds(140, 240, 50, 29);

        u.setText("U");
        getContentPane().add(u);
        u.setBounds(190, 240, 50, 29);

        v.setText("V");
        getContentPane().add(v);
        v.setBounds(240, 240, 50, 29);

        x.setText("X");
        getContentPane().add(x);
        x.setBounds(290, 240, 50, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jjlui\\Documents\\LITI\\3 semestre\\Programacion en Java\\FINAL\\EOYKfrx.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        area.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        a.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
        a.setBackground(Color.lightGray);// TODO add your handling code here:
    }//GEN-LAST:event_aMouseExited

    private void BMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseEntered
        B.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_BMouseEntered

    private void BMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseExited
        B.setBackground(Color.lightGray);        // TODO add your handling code here:
    }//GEN-LAST:event_BMouseExited

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortunaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortunaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortunaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortunaGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FortunaGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton a;
    private javax.swing.JTextArea area;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton n1;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    // End of variables declaration//GEN-END:variables
}
